spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_management_db
    username: postgres
    password: Chinnu@190897
    profiles:
      active: dev

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
app:
  jwt:
    secret: "mySuperSecretJwtKeyForLoanManagementApplication123456789"
    expiration-ms: 86400000
file:
  upload-dir: uploads